# Generated by Django 5.0.6 on 2024-05-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mecz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mecz',
            new_name='Mecze',
        ),
    ]
