# Generated by Django 5.0.6 on 2024-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_mecz_mecze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecze',
            name='logo_gospodarza',
            field=models.ImageField(upload_to='media/logos/'),
        ),
        migrations.AlterField(
            model_name='mecze',
            name='logo_przeciwnika',
            field=models.ImageField(upload_to='media/logos/'),
        ),
    ]
