# Generated by Django 5.0.6 on 2024-05-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mecze_logo_gospodarza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecze',
            name='logo_gospodarza',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='mecze',
            name='logo_przeciwnika',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
