# Generated by Django 5.0.6 on 2024-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_featured_post_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imienazwisko', models.CharField(max_length=50)),
                ('pozycja', models.CharField(max_length=50)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zespol/')),
            ],
        ),
    ]
